### ISSUE TITLE
Environment variable isn't automatically set

### ISSUE THREAD

**Issue by Selhar** [TallerWebSolutions/taller-test#16] opened 2019-01-25 14:09 UTC
OS: Fedora 29
Docker CE version: 18.09.01
The `GRAPHQL_HOST` variable isn't automatically set but it's required for the project to start. Manually setting it to  `http://localhost/graphql` solves the problem though.

**Comment by lucasconstantino** [comment] 2019-01-25 18:13
Hey, @Selhar, thanks for the heads-up!

Whey you say the variable isn't set, you mean inside the container? The `GRAPHQL_HOST` env is set via Dockerfile in this project, which means inside the container it should be properly working. Also, even though this project is composed of two quite distinct applications - Drupal, as backend; Next, as front-end - we decided for a single container environment to keep things simple, but it is completely feasible to run the front-end outside the container. In such a case, though, you must declare this variable manually, as in `GRAPHQL_HOST=http... yarn dev`.

Should you have any issue with that, please report back here ;)

**Comment by Selhar** [comment] 2019-01-25 18:33
Thanks for the feedback! I don't have experience with docker to give a more specific description, but just following the instructions (copy pasting) leads to the error. It happens in these steps:
`make in
cd next
yarn dev`
By the time `initApollo` is executed, the variable isn't set. Works perfectly after manually setting it though.

**Comment by lucasconstantino** [comment] 2019-01-25 19:03
Well, honestly I'm not able to reproduce it locally. I'll close the issue, and perhaps if someone reach this point with the same error we might gather more info on the reason. Thanks for reporting, anyway!

**Closed as completed by lucasconstantino** 2019-01-25 19:03 UTC
